[package]
name = "uncaught_exception"
version = "0.1.0"
edition = "2024"


[dependencies]
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
env_logger = "0.9"
reqwest = { version = "0.11", features = ["json"] }
thiserror = "1.0"
actix-http = "3"
